import ClientLayout from "./clientLayout";
import "./globals.css";
export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}